groups:
  - name: latency-quantiles
    interval: 1m
    rules:
      # Replace label matchers with your service/job labels
      - record: job:http_server_requests_seconds:rate5m_bucket
        expr: sum by (le, job) (rate(http_server_requests_seconds_bucket[5m]))

      - record: job:http_server_requests_seconds:p50
        expr: histogram_quantile(0.50, sum by (le, job) (rate(http_server_requests_seconds_bucket[5m])))

      - record: job:http_server_requests_seconds:p90
        expr: histogram_quantile(0.90, sum by (le, job) (rate(http_server_requests_seconds_bucket[5m])))

      - record: job:http_server_requests_seconds:p95
        expr: histogram_quantile(0.95, sum by (le, job) (rate(http_server_requests_seconds_bucket[5m])))

      - record: job:http_server_requests_seconds:p99
        expr: histogram_quantile(0.99, sum by (le, job) (rate(http_server_requests_seconds_bucket[5m])))

