name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: e-commerce-app
  CONTAINER_NAME: e-commerce-container
  SONAR_PROJECT_KEY: sonar-test-e-commerce_new-sonarscan
  SONAR_ORGANIZATION: sonar-test-e-commerce
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  # Job 1: Code Quality & Security Scanning
  code-analysis:
    runs-on: ubuntu-latest
    outputs:
      sonar-status: ${{ steps.sonar-check.outputs.status }}
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for SonarCloud analysis

      # Step 2: Set up Java for SonarCloud
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # Step 3: SonarCloud Scan
      - name: SonarCloud Scan
        id: sonar-scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=.
            -Dsonar.java.binaries=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
            -Dsonar.qualitygate.wait=true
            -Dsonar.branch.name=main

      # Step 4: Check SonarCloud Quality Gate status
      - name: Check SonarCloud Quality Gate
        id: sonar-check
        run: |
          echo "SonarCloud analysis completed with status: ${{ steps.sonar-scan.outputs.quality-gate-status }}"
          echo "status=${{ steps.sonar-scan.outputs.quality-gate-status }}" >> $GITHUB_OUTPUT

  # Job 2: Build and Security Scan (depends on code-analysis)
  build-and-scan:
    runs-on: ubuntu-latest
    needs: code-analysis
    if: needs.code-analysis.outputs.sonar-status == 'OK'
    
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 4: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:${{ github.sha }} .

      # Step 6: Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.ECR_REPOSITORY }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      # Step 7: Upload Trivy results to GitHub Security Dashboard
      - name: Upload Trivy results to GitHub Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  # Job 3: Notifications (runs after all jobs complete)
  notifications:
    runs-on: ubuntu-latest
    needs: [code-analysis, build-and-scan]
    if: always()
    
    steps:
      # Step 1: Send Success Notification
      - name: Send Slack Success Notification
        if: needs.code-analysis.result == 'success' && needs.build-and-scan.result == 'success'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"✅ *CI Pipeline Succeeded!*\nRepository: $GITHUB_REPOSITORY\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nSonarCloud: PASSED\nContainer Scan: PASSED\"}" \
          ${{ env.SLACK_WEBHOOK_URL }}

      # Step 2: Send Failure Notification
      - name: Send Slack Failure Notification
        if: needs.code-analysis.result == 'failure' || needs.build-and-scan.result == 'failure'
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"❌ *CI Pipeline Failed!*\nRepository: $GITHUB_REPOSITORY\nBranch: ${{ github.ref_name }}\nCommit: ${{ github.sha }}\nFailed Job: ${{ needs.*.result }}\"}" \
          ${{ env.SLACK_WEBHOOK_URL }}
